// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: rM_04RxMuJ

import * as React from 'react';

import Head from 'next/head';
import Link, { LinkProps } from 'next/link';
import { useRouter } from 'next/router';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { Heading } from '@chakra-ui/react'; // plasmic-import: 0G7l8BbhtHSG-/codeComponent
import { PageHeaderCentredOnAccent } from '../../chakra/chakraPro/Marketing/Page Headers/PageHeaderCentredOnAccent'; // plasmic-import: ipb5vL6-nrpb/codeComponent
import { PageHeaderWithCallToActions } from '../../chakra/chakraPro/Marketing/Page Headers/PageHeaderWithCallToActions'; // plasmic-import: vRLhHlbcIiI_/codeComponent
import { PageHeaderWithForm } from '../../chakra/chakraPro/Marketing/Page Headers/PageHeaderWithForm'; // plasmic-import: 0VKZk_JUSdWV/codeComponent
import { PageHeaderWithInput } from '../../chakra/chakraPro/Marketing/Page Headers/PageHeaderWithInput'; // plasmic-import: u1TRe0p0B73B/codeComponent
import { PageHeaderCentred } from '../../chakra/chakraPro/Marketing/Page Headers/PageHeaderCentred'; // plasmic-import: WOoayZH7UBKj/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_plasmic_poc_localhost.module.css'; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from './PlasmicPageHeadersMarketing.module.css'; // plasmic-import: rM_04RxMuJ/css

export type PlasmicPageHeadersMarketing__VariantMembers = {};
export type PlasmicPageHeadersMarketing__VariantsArgs = {};
type VariantPropType = keyof PlasmicPageHeadersMarketing__VariantsArgs;
export const PlasmicPageHeadersMarketing__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPageHeadersMarketing__ArgsType = {};
type ArgPropType = keyof PlasmicPageHeadersMarketing__ArgsType;
export const PlasmicPageHeadersMarketing__ArgProps = new Array<ArgPropType>();

export type PlasmicPageHeadersMarketing__OverridesType = {
  root?: p.Flex<'div'>;
  pageHeaderWithCallToActions?: p.Flex<typeof PageHeaderWithCallToActions>;
  pageHeaderWithForm?: p.Flex<typeof PageHeaderWithForm>;
  pageHeaderWithInput?: p.Flex<typeof PageHeaderWithInput>;
  pageHeaderCentred?: p.Flex<typeof PageHeaderCentred>;
};

export interface DefaultPageHeadersMarketingProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPageHeadersMarketing__RenderFunc(props: {
  variants: PlasmicPageHeadersMarketing__VariantsArgs;
  args: PlasmicPageHeadersMarketing__ArgsType;
  overrides: PlasmicPageHeadersMarketing__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={'root'}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__kOUt)}
            noOfLines={1 as const}
            size={'4xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pbdVr
              )}
            >
              {'Page Headers'}
            </div>
          </Heading>
          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__rBaAy)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hoiVo
              )}
            >
              {'Page header with input on accent'}
            </div>
          </Heading>
          <PageHeaderCentredOnAccent
            className={classNames(
              '__wab_instance',
              sty.pageHeaderCentredOnAccent__t4B
            )}
          />

          <Heading
            className={classNames(
              '__wab_instance',
              sty.chakraUiHeading___6SKex
            )}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__t6E5Q
              )}
            >
              {'Page header with call to actions'}
            </div>
          </Heading>
          <PageHeaderWithCallToActions
            data-plasmic-name={'pageHeaderWithCallToActions'}
            data-plasmic-override={overrides.pageHeaderWithCallToActions}
            className={classNames(
              '__wab_instance',
              sty.pageHeaderWithCallToActions
            )}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__o4YZj)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gia0C
              )}
            >
              {'Page header with form'}
            </div>
          </Heading>
          <PageHeaderWithForm
            data-plasmic-name={'pageHeaderWithForm'}
            data-plasmic-override={overrides.pageHeaderWithForm}
            className={classNames('__wab_instance', sty.pageHeaderWithForm)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__gDeW)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cn0Ht
              )}
            >
              {'Page header with input'}
            </div>
          </Heading>
          <PageHeaderWithInput
            data-plasmic-name={'pageHeaderWithInput'}
            data-plasmic-override={overrides.pageHeaderWithInput}
            className={classNames('__wab_instance', sty.pageHeaderWithInput)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__mk13I)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uhfQc
              )}
            >
              {'Page header centred on accent'}
            </div>
          </Heading>
          <PageHeaderCentredOnAccent
            className={classNames(
              '__wab_instance',
              sty.pageHeaderCentredOnAccent___6G36C
            )}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__iJcYn)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gZf1K
              )}
            >
              {'Page header centred'}
            </div>
          </Heading>
          <PageHeaderCentred
            data-plasmic-name={'pageHeaderCentred'}
            data-plasmic-override={overrides.pageHeaderCentred}
            className={classNames('__wab_instance', sty.pageHeaderCentred)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    'root',
    'pageHeaderWithCallToActions',
    'pageHeaderWithForm',
    'pageHeaderWithInput',
    'pageHeaderCentred',
  ],
  pageHeaderWithCallToActions: ['pageHeaderWithCallToActions'],
  pageHeaderWithForm: ['pageHeaderWithForm'],
  pageHeaderWithInput: ['pageHeaderWithInput'],
  pageHeaderCentred: ['pageHeaderCentred'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  pageHeaderWithCallToActions: typeof PageHeaderWithCallToActions;
  pageHeaderWithForm: typeof PageHeaderWithForm;
  pageHeaderWithInput: typeof PageHeaderWithInput;
  pageHeaderCentred: typeof PageHeaderCentred;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPageHeadersMarketing__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPageHeadersMarketing__VariantsArgs;
    args?: PlasmicPageHeadersMarketing__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPageHeadersMarketing__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPageHeadersMarketing__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPageHeadersMarketing__ArgProps,
          internalVariantPropNames: PlasmicPageHeadersMarketing__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicPageHeadersMarketing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicPageHeadersMarketing';
  } else {
    func.displayName = `PlasmicPageHeadersMarketing.${nodeName}`;
  }
  return func;
}

export const PlasmicPageHeadersMarketing = Object.assign(
  // Top-level PlasmicPageHeadersMarketing renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    pageHeaderWithCallToActions: makeNodeComponent(
      'pageHeaderWithCallToActions'
    ),
    pageHeaderWithForm: makeNodeComponent('pageHeaderWithForm'),
    pageHeaderWithInput: makeNodeComponent('pageHeaderWithInput'),
    pageHeaderCentred: makeNodeComponent('pageHeaderCentred'),

    // Metadata about props expected for PlasmicPageHeadersMarketing
    internalVariantProps: PlasmicPageHeadersMarketing__VariantProps,
    internalArgProps: PlasmicPageHeadersMarketing__ArgProps,

    // Page metadata
    pageMetadata: {
      title: '',
      description: '',
      ogImageSrc: '',
      canonical: '',
    },
  }
);

export default PlasmicPageHeadersMarketing;
/* prettier-ignore-end */
