// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: rBRoguPd71

import * as React from 'react';

import Head from 'next/head';
import Link, { LinkProps } from 'next/link';
import { useRouter } from 'next/router';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { Heading } from '@chakra-ui/react'; // plasmic-import: 0G7l8BbhtHSG-/codeComponent
import { StatWithCallToActionOnAccent } from '../../chakra/chakraPro/Marketing/Stats/StatWithCallToActionOnAccent'; // plasmic-import: xHh1h8SL7L5Q/codeComponent
import { StatWithCallToAction } from '../../chakra/chakraPro/Marketing/Stats/StatWithCallToAction'; // plasmic-import: rfeKVAhqravI/codeComponent
import { StatsOnBrand } from '../../chakra/chakraPro/Marketing/Stats/StatsOnBrand'; // plasmic-import: lbIabod64y9i/codeComponent
import { StatsWithDivider } from '../../chakra/chakraPro/Marketing/Stats/StatsWithDivider'; // plasmic-import: GKUluPwNCR0I/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_plasmic_poc_localhost.module.css'; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from './PlasmicStatsMarketing.module.css'; // plasmic-import: rBRoguPd71/css

export type PlasmicStatsMarketing__VariantMembers = {};
export type PlasmicStatsMarketing__VariantsArgs = {};
type VariantPropType = keyof PlasmicStatsMarketing__VariantsArgs;
export const PlasmicStatsMarketing__VariantProps = new Array<VariantPropType>();

export type PlasmicStatsMarketing__ArgsType = {};
type ArgPropType = keyof PlasmicStatsMarketing__ArgsType;
export const PlasmicStatsMarketing__ArgProps = new Array<ArgPropType>();

export type PlasmicStatsMarketing__OverridesType = {
  root?: p.Flex<'div'>;
  statWithCallToActionOnAccent?: p.Flex<typeof StatWithCallToActionOnAccent>;
  statWithCallToAction?: p.Flex<typeof StatWithCallToAction>;
  statsOnBrand?: p.Flex<typeof StatsOnBrand>;
  statsWithDivider?: p.Flex<typeof StatsWithDivider>;
};

export interface DefaultStatsMarketingProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStatsMarketing__RenderFunc(props: {
  variants: PlasmicStatsMarketing__VariantsArgs;
  args: PlasmicStatsMarketing__ArgsType;
  overrides: PlasmicStatsMarketing__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={'root'}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__seZaj)}
            noOfLines={1 as const}
            size={'4xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7Z4ML
              )}
            >
              {'Stats'}
            </div>
          </Heading>
          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__knxsv)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jzTv8
              )}
            >
              {'Stat with call to action on accent'}
            </div>
          </Heading>
          <StatWithCallToActionOnAccent
            data-plasmic-name={'statWithCallToActionOnAccent'}
            data-plasmic-override={overrides.statWithCallToActionOnAccent}
            className={classNames(
              '__wab_instance',
              sty.statWithCallToActionOnAccent
            )}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__bjoUa)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2ZmTd
              )}
            >
              {'Stat with call to action'}
            </div>
          </Heading>
          <StatWithCallToAction
            data-plasmic-name={'statWithCallToAction'}
            data-plasmic-override={overrides.statWithCallToAction}
            className={classNames('__wab_instance', sty.statWithCallToAction)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__iDwkC)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xmC7Q
              )}
            >
              {'Stats on brand'}
            </div>
          </Heading>
          <StatsOnBrand
            data-plasmic-name={'statsOnBrand'}
            data-plasmic-override={overrides.statsOnBrand}
            className={classNames('__wab_instance', sty.statsOnBrand)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__muF9)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ib7Pr
              )}
            >
              {'Stats with divider'}
            </div>
          </Heading>
          <StatsWithDivider
            data-plasmic-name={'statsWithDivider'}
            data-plasmic-override={overrides.statsWithDivider}
            className={classNames('__wab_instance', sty.statsWithDivider)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    'root',
    'statWithCallToActionOnAccent',
    'statWithCallToAction',
    'statsOnBrand',
    'statsWithDivider',
  ],
  statWithCallToActionOnAccent: ['statWithCallToActionOnAccent'],
  statWithCallToAction: ['statWithCallToAction'],
  statsOnBrand: ['statsOnBrand'],
  statsWithDivider: ['statsWithDivider'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  statWithCallToActionOnAccent: typeof StatWithCallToActionOnAccent;
  statWithCallToAction: typeof StatWithCallToAction;
  statsOnBrand: typeof StatsOnBrand;
  statsWithDivider: typeof StatsWithDivider;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStatsMarketing__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStatsMarketing__VariantsArgs;
    args?: PlasmicStatsMarketing__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStatsMarketing__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStatsMarketing__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicStatsMarketing__ArgProps,
          internalVariantPropNames: PlasmicStatsMarketing__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicStatsMarketing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicStatsMarketing';
  } else {
    func.displayName = `PlasmicStatsMarketing.${nodeName}`;
  }
  return func;
}

export const PlasmicStatsMarketing = Object.assign(
  // Top-level PlasmicStatsMarketing renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    statWithCallToActionOnAccent: makeNodeComponent(
      'statWithCallToActionOnAccent'
    ),
    statWithCallToAction: makeNodeComponent('statWithCallToAction'),
    statsOnBrand: makeNodeComponent('statsOnBrand'),
    statsWithDivider: makeNodeComponent('statsWithDivider'),

    // Metadata about props expected for PlasmicStatsMarketing
    internalVariantProps: PlasmicStatsMarketing__VariantProps,
    internalArgProps: PlasmicStatsMarketing__ArgProps,

    // Page metadata
    pageMetadata: {
      title: '',
      description: '',
      ogImageSrc: '',
      canonical: '',
    },
  }
);

export default PlasmicStatsMarketing;
/* prettier-ignore-end */
