// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: nGZXZfZX5f

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Heading } from "@chakra-ui/react"; // plasmic-import: 0G7l8BbhtHSG-/codeComponent
import { CountdownOnBlack } from "../../custom/chakraPro/CountdownOnBlack"; // plasmic-import: wSk9_Vffcdgt/codeComponent
import { CountdownOnColoredBackground } from "../../custom/chakraPro/CountdownOnColoredBackground"; // plasmic-import: 60SBWxDOKQzV/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_poc_localhost.module.css"; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from "./PlasmicCountdownTimer.module.css"; // plasmic-import: nGZXZfZX5f/css

export type PlasmicCountdownTimer__VariantMembers = {};
export type PlasmicCountdownTimer__VariantsArgs = {};
type VariantPropType = keyof PlasmicCountdownTimer__VariantsArgs;
export const PlasmicCountdownTimer__VariantProps = new Array<VariantPropType>();

export type PlasmicCountdownTimer__ArgsType = {};
type ArgPropType = keyof PlasmicCountdownTimer__ArgsType;
export const PlasmicCountdownTimer__ArgProps = new Array<ArgPropType>();

export type PlasmicCountdownTimer__OverridesType = {
  root?: p.Flex<"div">;
  countdownOnBlack?: p.Flex<typeof CountdownOnBlack>;
  countdownOnColoredBackground?: p.Flex<typeof CountdownOnColoredBackground>;
};

export interface DefaultCountdownTimerProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCountdownTimer__RenderFunc(props: {
  variants: PlasmicCountdownTimer__VariantsArgs;
  args: PlasmicCountdownTimer__ArgsType;
  overrides: PlasmicCountdownTimer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__fh0X5)}
            noOfLines={1 as const}
            size={"4xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fLcz9
              )}
            >
              {"Countdown Timer"}
            </div>
          </Heading>
          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__jNtWp)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5UWug
              )}
            >
              {"Countdown on black"}
            </div>
          </Heading>
          <CountdownOnBlack
            data-plasmic-name={"countdownOnBlack"}
            data-plasmic-override={overrides.countdownOnBlack}
            className={classNames("__wab_instance", sty.countdownOnBlack)}
          />

          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__urnZf)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3AoBj
              )}
            >
              {"xxxxxxx"}
            </div>
          </Heading>
          <CountdownOnColoredBackground
            data-plasmic-name={"countdownOnColoredBackground"}
            data-plasmic-override={overrides.countdownOnColoredBackground}
            className={classNames(
              "__wab_instance",
              sty.countdownOnColoredBackground
            )}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "countdownOnBlack", "countdownOnColoredBackground"],
  countdownOnBlack: ["countdownOnBlack"],
  countdownOnColoredBackground: ["countdownOnColoredBackground"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  countdownOnBlack: typeof CountdownOnBlack;
  countdownOnColoredBackground: typeof CountdownOnColoredBackground;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCountdownTimer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCountdownTimer__VariantsArgs;
    args?: PlasmicCountdownTimer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCountdownTimer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCountdownTimer__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCountdownTimer__ArgProps,
          internalVariantPropNames: PlasmicCountdownTimer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCountdownTimer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCountdownTimer";
  } else {
    func.displayName = `PlasmicCountdownTimer.${nodeName}`;
  }
  return func;
}

export const PlasmicCountdownTimer = Object.assign(
  // Top-level PlasmicCountdownTimer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    countdownOnBlack: makeNodeComponent("countdownOnBlack"),
    countdownOnColoredBackground: makeNodeComponent(
      "countdownOnColoredBackground"
    ),

    // Metadata about props expected for PlasmicCountdownTimer
    internalVariantProps: PlasmicCountdownTimer__VariantProps,
    internalArgProps: PlasmicCountdownTimer__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCountdownTimer;
/* prettier-ignore-end */
