// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: zumJsUKunp

import * as React from 'react';

import Head from 'next/head';
import Link, { LinkProps } from 'next/link';
import { useRouter } from 'next/router';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { LoginWithCentredForm } from '../../chakra/chakraPro/Application/Authentication/LoginWithCentredForm'; // plasmic-import: PZuCg-eLQu/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_plasmic_poc_localhost.module.css'; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from './PlasmicLoginWithCentredForm.module.css'; // plasmic-import: zumJsUKunp/css

export type PlasmicLoginWithCentredForm__VariantMembers = {};
export type PlasmicLoginWithCentredForm__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginWithCentredForm__VariantsArgs;
export const PlasmicLoginWithCentredForm__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLoginWithCentredForm__ArgsType = {};
type ArgPropType = keyof PlasmicLoginWithCentredForm__ArgsType;
export const PlasmicLoginWithCentredForm__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginWithCentredForm__OverridesType = {
  root?: p.Flex<'div'>;
  loginWithCentredForm?: p.Flex<typeof LoginWithCentredForm>;
};

export interface DefaultLoginWithCentredFormProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLoginWithCentredForm__RenderFunc(props: {
  variants: PlasmicLoginWithCentredForm__VariantsArgs;
  args: PlasmicLoginWithCentredForm__ArgsType;
  overrides: PlasmicLoginWithCentredForm__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <LoginWithCentredForm
        data-plasmic-name={'loginWithCentredForm'}
        data-plasmic-override={overrides.loginWithCentredForm}
        className={classNames('__wab_instance', sty.loginWithCentredForm)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'loginWithCentredForm'],
  loginWithCentredForm: ['loginWithCentredForm'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  loginWithCentredForm: typeof LoginWithCentredForm;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginWithCentredForm__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginWithCentredForm__VariantsArgs;
    args?: PlasmicLoginWithCentredForm__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLoginWithCentredForm__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLoginWithCentredForm__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLoginWithCentredForm__ArgProps,
          internalVariantPropNames: PlasmicLoginWithCentredForm__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicLoginWithCentredForm__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicLoginWithCentredForm';
  } else {
    func.displayName = `PlasmicLoginWithCentredForm.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginWithCentredForm = Object.assign(
  // Top-level PlasmicLoginWithCentredForm renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    loginWithCentredForm: makeNodeComponent('loginWithCentredForm'),

    // Metadata about props expected for PlasmicLoginWithCentredForm
    internalVariantProps: PlasmicLoginWithCentredForm__VariantProps,
    internalArgProps: PlasmicLoginWithCentredForm__ArgProps,
  }
);

export default PlasmicLoginWithCentredForm;
/* prettier-ignore-end */
