// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: YKR4hXK5QC

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Heading } from "@chakra-ui/react"; // plasmic-import: 0G7l8BbhtHSG-/codeComponent
import { ListWithAvatar } from "../../custom/chakraPro/Aplication/Lists/ListWithAvatar"; // plasmic-import: MYDf-TWOuMd/codeComponent
import { ListWithTruncatedPreview } from "../../custom/chakraPro/Aplication/Lists/ListWithTruncatedPreview"; // plasmic-import: jhbrk1p4IvR/codeComponent
import { ListWithDraggableElements } from "../../custom/chakraPro/Aplication/Lists/ListWithDraggableElements"; // plasmic-import: uadThA52p4w/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_poc_localhost.module.css"; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from "./PlasmicLists.module.css"; // plasmic-import: YKR4hXK5QC/css

export type PlasmicLists__VariantMembers = {};
export type PlasmicLists__VariantsArgs = {};
type VariantPropType = keyof PlasmicLists__VariantsArgs;
export const PlasmicLists__VariantProps = new Array<VariantPropType>();

export type PlasmicLists__ArgsType = {};
type ArgPropType = keyof PlasmicLists__ArgsType;
export const PlasmicLists__ArgProps = new Array<ArgPropType>();

export type PlasmicLists__OverridesType = {
  root?: p.Flex<"div">;
  listWithAvatar?: p.Flex<typeof ListWithAvatar>;
  listWithTruncatedPreview?: p.Flex<typeof ListWithTruncatedPreview>;
  listWithDraggableElements?: p.Flex<typeof ListWithDraggableElements>;
};

export interface DefaultListsProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLists__RenderFunc(props: {
  variants: PlasmicLists__VariantsArgs;
  args: PlasmicLists__ArgsType;
  overrides: PlasmicLists__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Heading
            className={classNames(
              "__wab_instance",
              sty.chakraUiHeading___9Fx0F
            )}
            noOfLines={1 as const}
            size={"4xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zk0W
              )}
            >
              {"Lists"}
            </div>
          </Heading>
          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__pXkkW)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cwS7K
              )}
            >
              {"List with avatar"}
            </div>
          </Heading>
          <ListWithAvatar
            data-plasmic-name={"listWithAvatar"}
            data-plasmic-override={overrides.listWithAvatar}
            className={classNames("__wab_instance", sty.listWithAvatar)}
          />

          <Heading
            className={classNames(
              "__wab_instance",
              sty.chakraUiHeading___6Oo89
            )}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__szCmb
              )}
            >
              {"List with truncated preview"}
            </div>
          </Heading>
          <ListWithTruncatedPreview
            data-plasmic-name={"listWithTruncatedPreview"}
            data-plasmic-override={overrides.listWithTruncatedPreview}
            className={classNames(
              "__wab_instance",
              sty.listWithTruncatedPreview
            )}
          />

          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__k1CtM)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bBpe9
              )}
            >
              {"List with draggable elements"}
            </div>
            <ListWithDraggableElements
              data-plasmic-name={"listWithDraggableElements"}
              data-plasmic-override={overrides.listWithDraggableElements}
              className={classNames(
                "__wab_instance",
                sty.listWithDraggableElements
              )}
            />
          </Heading>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "listWithAvatar",
    "listWithTruncatedPreview",
    "listWithDraggableElements"
  ],
  listWithAvatar: ["listWithAvatar"],
  listWithTruncatedPreview: ["listWithTruncatedPreview"],
  listWithDraggableElements: ["listWithDraggableElements"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  listWithAvatar: typeof ListWithAvatar;
  listWithTruncatedPreview: typeof ListWithTruncatedPreview;
  listWithDraggableElements: typeof ListWithDraggableElements;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLists__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLists__VariantsArgs;
    args?: PlasmicLists__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLists__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLists__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLists__ArgProps,
          internalVariantPropNames: PlasmicLists__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLists__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLists";
  } else {
    func.displayName = `PlasmicLists.${nodeName}`;
  }
  return func;
}

export const PlasmicLists = Object.assign(
  // Top-level PlasmicLists renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    listWithAvatar: makeNodeComponent("listWithAvatar"),
    listWithTruncatedPreview: makeNodeComponent("listWithTruncatedPreview"),
    listWithDraggableElements: makeNodeComponent("listWithDraggableElements"),

    // Metadata about props expected for PlasmicLists
    internalVariantProps: PlasmicLists__VariantProps,
    internalArgProps: PlasmicLists__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLists;
/* prettier-ignore-end */
