// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: QuauOu8eXx

import * as React from 'react';

import Head from 'next/head';
import Link, { LinkProps } from 'next/link';
import { useRouter } from 'next/router';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { Accordion } from '@chakra-ui/react'; // plasmic-import: 2KAN9pHJgUTnhu/codeComponent
import { AccordionItem } from '@chakra-ui/react'; // plasmic-import: i21aTMORw6/codeComponent
import { AccordionButton } from '@chakra-ui/react'; // plasmic-import: BaAYoc7wxa/codeComponent
import { AccordionIcon } from '@chakra-ui/react'; // plasmic-import: ZgWEbLwSSK/codeComponent
import { AccordionPanel } from '@chakra-ui/react'; // plasmic-import: 17VrZJ3mR8/codeComponent
import { Text } from '@chakra-ui/react'; // plasmic-import: SdN14ngBJybRru/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_plasmic_poc_localhost.module.css'; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from './PlasmicAccordion.module.css'; // plasmic-import: QuauOu8eXx/css

export type PlasmicAccordion__VariantMembers = {};
export type PlasmicAccordion__VariantsArgs = {};
type VariantPropType = keyof PlasmicAccordion__VariantsArgs;
export const PlasmicAccordion__VariantProps = new Array<VariantPropType>();

export type PlasmicAccordion__ArgsType = {};
type ArgPropType = keyof PlasmicAccordion__ArgsType;
export const PlasmicAccordion__ArgProps = new Array<ArgPropType>();

export type PlasmicAccordion__OverridesType = {
  root?: p.Flex<'div'>;
  chakraUiAccordion?: p.Flex<typeof Accordion>;
};

export interface DefaultAccordionProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAccordion__RenderFunc(props: {
  variants: PlasmicAccordion__VariantsArgs;
  args: PlasmicAccordion__ArgsType;
  overrides: PlasmicAccordion__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={'root'}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Accordion
            data-plasmic-name={'chakraUiAccordion'}
            data-plasmic-override={overrides.chakraUiAccordion}
            allowMultiple={false}
            allowToggle={false}
            className={classNames('__wab_instance', sty.chakraUiAccordion)}
            defaultIndex={1 as const}
            reduceMotion={false}
          >
            <AccordionItem
              className={classNames(
                '__wab_instance',
                sty.chakraUiAccordionItem__j1Vzu
              )}
            >
              <AccordionButton
                _expanded={{ bg: 'orange', color: 'red' }}
                className={classNames(
                  '__wab_instance',
                  sty.chakraUiAccordionButton__ryJgz
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eGdO5
                  )}
                >
                  {'Section 1 title'}
                </div>
                <AccordionIcon
                  className={classNames(
                    '__wab_instance',
                    sty.chakraUiAccordionIcon__mAdN4
                  )}
                />
              </AccordionButton>
              <AccordionPanel
                className={classNames(
                  '__wab_instance',
                  sty.chakraUiAccordionPanel__dyJl6
                )}
              >
                <Text
                  className={classNames(
                    '__wab_instance',
                    sty.chakraUiText__pTfa
                  )}
                  fontStyle={'normal' as const}
                  size={'md' as const}
                  variant={'regular' as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c7JS
                    )}
                  >
                    {
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
                    }
                  </div>
                </Text>
              </AccordionPanel>
            </AccordionItem>
            <AccordionItem
              className={classNames(
                '__wab_instance',
                sty.chakraUiAccordionItem__pLHww
              )}
            >
              <AccordionButton
                className={classNames(
                  '__wab_instance',
                  sty.chakraUiAccordionButton__iyiBo
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dLrX
                  )}
                >
                  {'Section 1 title'}
                </div>
                <AccordionIcon
                  className={classNames(
                    '__wab_instance',
                    sty.chakraUiAccordionIcon__lmzTk
                  )}
                />
              </AccordionButton>
              <AccordionPanel
                className={classNames(
                  '__wab_instance',
                  sty.chakraUiAccordionPanel___8F8W6
                )}
              >
                <Text
                  className={classNames(
                    '__wab_instance',
                    sty.chakraUiText__sekq
                  )}
                  fontStyle={'normal' as const}
                  size={'md' as const}
                  variant={'regular' as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9LgOw
                    )}
                  >
                    {
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
                    }
                  </div>
                </Text>
              </AccordionPanel>
            </AccordionItem>
          </Accordion>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'chakraUiAccordion'],
  chakraUiAccordion: ['chakraUiAccordion'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  chakraUiAccordion: typeof Accordion;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAccordion__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAccordion__VariantsArgs;
    args?: PlasmicAccordion__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAccordion__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAccordion__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAccordion__ArgProps,
          internalVariantPropNames: PlasmicAccordion__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicAccordion__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicAccordion';
  } else {
    func.displayName = `PlasmicAccordion.${nodeName}`;
  }
  return func;
}

export const PlasmicAccordion = Object.assign(
  // Top-level PlasmicAccordion renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    chakraUiAccordion: makeNodeComponent('chakraUiAccordion'),

    // Metadata about props expected for PlasmicAccordion
    internalVariantProps: PlasmicAccordion__VariantProps,
    internalArgProps: PlasmicAccordion__ArgProps,

    // Page metadata
    pageMetadata: {
      title: '',
      description: '',
      ogImageSrc: '',
      canonical: '',
    },
  }
);

export default PlasmicAccordion;
/* prettier-ignore-end */
