// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: 9CBuJmkqGz

import * as React from 'react';

import Head from 'next/head';
import Link, { LinkProps } from 'next/link';
import { useRouter } from 'next/router';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/react-web/lib/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';
import { Heading } from '@chakra-ui/react'; // plasmic-import: 0G7l8BbhtHSG-/codeComponent
import { PricingWithCornerBadge } from '../../chakra/chakraPro/Marketing/Pricing/PricingWithCornerBadge'; // plasmic-import: 2WDaZrTMVftj/codeComponent
import { PricingWithTable } from '../../chakra/chakraPro/Marketing/Pricing/PricingWithTable'; // plasmic-import: pmY_lwk_gSs3/codeComponent
import { PricingWithOneTier } from '../../chakra/chakraPro/Marketing/Pricing/PricingWithOneTier'; // plasmic-import: 8bgbNssWm3qk/codeComponent
import { PricingWithTwoTiers } from '../../chakra/chakraPro/Marketing/Pricing/PricingWithTwoTiers'; // plasmic-import: CU5InQRmYKx8/codeComponent
import { PricingWithThreeTiers } from '../../chakra/chakraPro/Marketing/Pricing/PricingWithThreeTiers'; // plasmic-import: uKdWDZ7PXmil/codeComponent
import { WithFlushedCards } from '../../chakra/chakraPro/Marketing/Pricing/WithFlushedCards'; // plasmic-import: Z3mR0qONoa72/codeComponent
import { ThreeTiersWithToggle } from '../../chakra/chakraPro/Marketing/Pricing/ThreeTiersWithToggle'; // plasmic-import: 9--KfKNuZUEp/codeComponent
import { TwoTiersWithBottomBlock } from '../../chakra/chakraPro/Marketing/Pricing/TwoTiersWithBottomBlock'; // plasmic-import: GYF0gf41uLgk/codeComponent
import { MultiColored } from '../../chakra/chakraPro/Marketing/Pricing/MultiColored'; // plasmic-import: nrz3USlVoErV/codeComponent

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_plasmic_poc_localhost.module.css'; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from './PlasmicPricingMarketing.module.css'; // plasmic-import: 9CBuJmkqGz/css

export type PlasmicPricingMarketing__VariantMembers = {};
export type PlasmicPricingMarketing__VariantsArgs = {};
type VariantPropType = keyof PlasmicPricingMarketing__VariantsArgs;
export const PlasmicPricingMarketing__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPricingMarketing__ArgsType = {};
type ArgPropType = keyof PlasmicPricingMarketing__ArgsType;
export const PlasmicPricingMarketing__ArgProps = new Array<ArgPropType>();

export type PlasmicPricingMarketing__OverridesType = {
  root?: p.Flex<'div'>;
  pricingWithCornerBadge?: p.Flex<typeof PricingWithCornerBadge>;
  pricingWithTable?: p.Flex<typeof PricingWithTable>;
  pricingWithOneTier?: p.Flex<typeof PricingWithOneTier>;
  pricingWithTwoTiers?: p.Flex<typeof PricingWithTwoTiers>;
  pricingWithThreeTiers?: p.Flex<typeof PricingWithThreeTiers>;
  withFlushedCards?: p.Flex<typeof WithFlushedCards>;
  threeTiersWithToggle?: p.Flex<typeof ThreeTiersWithToggle>;
  twoTiersWithBottomBlock?: p.Flex<typeof TwoTiersWithBottomBlock>;
  multiColored?: p.Flex<typeof MultiColored>;
};

export interface DefaultPricingMarketingProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPricingMarketing__RenderFunc(props: {
  variants: PlasmicPricingMarketing__VariantsArgs;
  args: PlasmicPricingMarketing__ArgsType;
  overrides: PlasmicPricingMarketing__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={'root'}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__eBZx)}
            noOfLines={1 as const}
            size={'4xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__e66To
              )}
            >
              {'Pricing'}
            </div>
          </Heading>
          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__w9Knx)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wDvBv
              )}
            >
              {'Pricing with corner badge'}
            </div>
          </Heading>
          <PricingWithCornerBadge
            data-plasmic-name={'pricingWithCornerBadge'}
            data-plasmic-override={overrides.pricingWithCornerBadge}
            className={classNames('__wab_instance', sty.pricingWithCornerBadge)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__objTm)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lmUqy
              )}
            >
              {'Pricing with table'}
            </div>
          </Heading>
          <PricingWithTable
            data-plasmic-name={'pricingWithTable'}
            data-plasmic-override={overrides.pricingWithTable}
            className={classNames('__wab_instance', sty.pricingWithTable)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__pWhjg)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nPqUd
              )}
            >
              {'Pricing with one tier'}
            </div>
          </Heading>
          <PricingWithOneTier
            data-plasmic-name={'pricingWithOneTier'}
            data-plasmic-override={overrides.pricingWithOneTier}
            className={classNames('__wab_instance', sty.pricingWithOneTier)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__pl0YH)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rwAWf
              )}
            >
              {'Pricing with two tiers'}
            </div>
          </Heading>
          <PricingWithTwoTiers
            data-plasmic-name={'pricingWithTwoTiers'}
            data-plasmic-override={overrides.pricingWithTwoTiers}
            className={classNames('__wab_instance', sty.pricingWithTwoTiers)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__kpYd8)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__maHpd
              )}
            >
              {'Pricing with three tiers'}
            </div>
          </Heading>
          <PricingWithThreeTiers
            data-plasmic-name={'pricingWithThreeTiers'}
            data-plasmic-override={overrides.pricingWithThreeTiers}
            className={classNames('__wab_instance', sty.pricingWithThreeTiers)}
          />

          <Heading
            className={classNames('__wab_instance', sty.chakraUiHeading__ggzJ)}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__u1GAv
              )}
            >
              {'With flushed cards'}
            </div>
          </Heading>
          <WithFlushedCards
            data-plasmic-name={'withFlushedCards'}
            data-plasmic-override={overrides.withFlushedCards}
            className={classNames('__wab_instance', sty.withFlushedCards)}
          />

          <Heading
            className={classNames(
              '__wab_instance',
              sty.chakraUiHeading___1Lzwi
            )}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zrKb4
              )}
            >
              {'Three tiers with toggle'}
            </div>
          </Heading>
          <ThreeTiersWithToggle
            data-plasmic-name={'threeTiersWithToggle'}
            data-plasmic-override={overrides.threeTiersWithToggle}
            className={classNames('__wab_instance', sty.threeTiersWithToggle)}
          />

          <Heading
            className={classNames(
              '__wab_instance',
              sty.chakraUiHeading___9Wn9T
            )}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oZ3D
              )}
            >
              {'Two tiers with bottom block'}
            </div>
          </Heading>
          <TwoTiersWithBottomBlock
            data-plasmic-name={'twoTiersWithBottomBlock'}
            data-plasmic-override={overrides.twoTiersWithBottomBlock}
            className={classNames(
              '__wab_instance',
              sty.twoTiersWithBottomBlock
            )}
          />

          <Heading
            className={classNames(
              '__wab_instance',
              sty.chakraUiHeading___4BNy3
            )}
            noOfLines={1 as const}
            size={'xl' as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___78Ll
              )}
            >
              {'Multi colored'}
            </div>
          </Heading>
          <MultiColored
            data-plasmic-name={'multiColored'}
            data-plasmic-override={overrides.multiColored}
            className={classNames('__wab_instance', sty.multiColored)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    'root',
    'pricingWithCornerBadge',
    'pricingWithTable',
    'pricingWithOneTier',
    'pricingWithTwoTiers',
    'pricingWithThreeTiers',
    'withFlushedCards',
    'threeTiersWithToggle',
    'twoTiersWithBottomBlock',
    'multiColored',
  ],
  pricingWithCornerBadge: ['pricingWithCornerBadge'],
  pricingWithTable: ['pricingWithTable'],
  pricingWithOneTier: ['pricingWithOneTier'],
  pricingWithTwoTiers: ['pricingWithTwoTiers'],
  pricingWithThreeTiers: ['pricingWithThreeTiers'],
  withFlushedCards: ['withFlushedCards'],
  threeTiersWithToggle: ['threeTiersWithToggle'],
  twoTiersWithBottomBlock: ['twoTiersWithBottomBlock'],
  multiColored: ['multiColored'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: 'div';
  pricingWithCornerBadge: typeof PricingWithCornerBadge;
  pricingWithTable: typeof PricingWithTable;
  pricingWithOneTier: typeof PricingWithOneTier;
  pricingWithTwoTiers: typeof PricingWithTwoTiers;
  pricingWithThreeTiers: typeof PricingWithThreeTiers;
  withFlushedCards: typeof WithFlushedCards;
  threeTiersWithToggle: typeof ThreeTiersWithToggle;
  twoTiersWithBottomBlock: typeof TwoTiersWithBottomBlock;
  multiColored: typeof MultiColored;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPricingMarketing__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPricingMarketing__VariantsArgs;
    args?: PlasmicPricingMarketing__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPricingMarketing__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPricingMarketing__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPricingMarketing__ArgProps,
          internalVariantPropNames: PlasmicPricingMarketing__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicPricingMarketing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicPricingMarketing';
  } else {
    func.displayName = `PlasmicPricingMarketing.${nodeName}`;
  }
  return func;
}

export const PlasmicPricingMarketing = Object.assign(
  // Top-level PlasmicPricingMarketing renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    pricingWithCornerBadge: makeNodeComponent('pricingWithCornerBadge'),
    pricingWithTable: makeNodeComponent('pricingWithTable'),
    pricingWithOneTier: makeNodeComponent('pricingWithOneTier'),
    pricingWithTwoTiers: makeNodeComponent('pricingWithTwoTiers'),
    pricingWithThreeTiers: makeNodeComponent('pricingWithThreeTiers'),
    withFlushedCards: makeNodeComponent('withFlushedCards'),
    threeTiersWithToggle: makeNodeComponent('threeTiersWithToggle'),
    twoTiersWithBottomBlock: makeNodeComponent('twoTiersWithBottomBlock'),
    multiColored: makeNodeComponent('multiColored'),

    // Metadata about props expected for PlasmicPricingMarketing
    internalVariantProps: PlasmicPricingMarketing__VariantProps,
    internalArgProps: PlasmicPricingMarketing__ArgProps,

    // Page metadata
    pageMetadata: {
      title: '',
      description: '',
      ogImageSrc: '',
      canonical: '',
    },
  }
);

export default PlasmicPricingMarketing;
/* prettier-ignore-end */
