// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nV7sRTPBx6ecWzFNNAWeQg
// Component: cBdpKj_F4u

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Heading } from "@chakra-ui/react"; // plasmic-import: 0G7l8BbhtHSG-/codeComponent
import { NavbarWithTwoRows } from "../../custom/chakraPro/Aplication/Navbars/NavbarWithTwoRows"; // plasmic-import: yJff6CWBPde/codeComponent
import { NavbarWithTwoRowsOnAccent } from "../../custom/chakraPro/Aplication/Navbars/NavbarWithTwoRowsOnAccent"; // plasmic-import: KOUGqjNdd6L/codeComponent
import { NavbarWithAvatarOnAccent } from "../../custom/chakraPro/Aplication/Navbars/NavbarWithAvatarOnAccent"; // plasmic-import: c6sn-jmfLCW/codeComponent
import { NavbarWithAvatar } from "../../custom/chakraPro/Aplication/Navbars/NavbarWithAvatar"; // plasmic-import: HPiHQtoXgV7/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_poc_localhost.module.css"; // plasmic-import: nV7sRTPBx6ecWzFNNAWeQg/projectcss
import sty from "./PlasmicNavbars.module.css"; // plasmic-import: cBdpKj_F4u/css

export type PlasmicNavbars__VariantMembers = {};
export type PlasmicNavbars__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavbars__VariantsArgs;
export const PlasmicNavbars__VariantProps = new Array<VariantPropType>();

export type PlasmicNavbars__ArgsType = {};
type ArgPropType = keyof PlasmicNavbars__ArgsType;
export const PlasmicNavbars__ArgProps = new Array<ArgPropType>();

export type PlasmicNavbars__OverridesType = {
  root?: p.Flex<"div">;
  navbarWithTwoRows?: p.Flex<typeof NavbarWithTwoRows>;
  navbarWithTwoRowsOnAccent?: p.Flex<typeof NavbarWithTwoRowsOnAccent>;
  navbarWithAvatarOnAccent?: p.Flex<typeof NavbarWithAvatarOnAccent>;
  navbarWithAvatar?: p.Flex<typeof NavbarWithAvatar>;
};

export interface DefaultNavbarsProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbars__RenderFunc(props: {
  variants: PlasmicNavbars__VariantsArgs;
  args: PlasmicNavbars__ArgsType;
  overrides: PlasmicNavbars__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__gmGXh)}
            noOfLines={1 as const}
            size={"4xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__llboW
              )}
            >
              {"Navbars"}
            </div>
          </Heading>
          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__hlW0Q)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lh8Sc
              )}
            >
              {"Navbar with two rows"}
            </div>
          </Heading>
          <NavbarWithTwoRows
            data-plasmic-name={"navbarWithTwoRows"}
            data-plasmic-override={overrides.navbarWithTwoRows}
            className={classNames("__wab_instance", sty.navbarWithTwoRows)}
          />

          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__bAYsE)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5VdXr
              )}
            >
              {"Navbar with two rows on accent"}
            </div>
          </Heading>
          <NavbarWithTwoRowsOnAccent
            data-plasmic-name={"navbarWithTwoRowsOnAccent"}
            data-plasmic-override={overrides.navbarWithTwoRowsOnAccent}
            className={classNames(
              "__wab_instance",
              sty.navbarWithTwoRowsOnAccent
            )}
          />

          <Heading
            className={classNames(
              "__wab_instance",
              sty.chakraUiHeading___6Nl0O
            )}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oDdkw
              )}
            >
              {"Navbar with avatar on accent"}
            </div>
          </Heading>
          <NavbarWithAvatarOnAccent
            data-plasmic-name={"navbarWithAvatarOnAccent"}
            data-plasmic-override={overrides.navbarWithAvatarOnAccent}
            className={classNames(
              "__wab_instance",
              sty.navbarWithAvatarOnAccent
            )}
          />

          <Heading
            className={classNames("__wab_instance", sty.chakraUiHeading__sq1NG)}
            noOfLines={1 as const}
            size={"xl" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nsPy9
              )}
            >
              {"Navbar with avatar"}
            </div>
          </Heading>
          <NavbarWithAvatar
            data-plasmic-name={"navbarWithAvatar"}
            data-plasmic-override={overrides.navbarWithAvatar}
            className={classNames("__wab_instance", sty.navbarWithAvatar)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbarWithTwoRows",
    "navbarWithTwoRowsOnAccent",
    "navbarWithAvatarOnAccent",
    "navbarWithAvatar"
  ],
  navbarWithTwoRows: ["navbarWithTwoRows"],
  navbarWithTwoRowsOnAccent: ["navbarWithTwoRowsOnAccent"],
  navbarWithAvatarOnAccent: ["navbarWithAvatarOnAccent"],
  navbarWithAvatar: ["navbarWithAvatar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbarWithTwoRows: typeof NavbarWithTwoRows;
  navbarWithTwoRowsOnAccent: typeof NavbarWithTwoRowsOnAccent;
  navbarWithAvatarOnAccent: typeof NavbarWithAvatarOnAccent;
  navbarWithAvatar: typeof NavbarWithAvatar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbars__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbars__VariantsArgs;
    args?: PlasmicNavbars__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavbars__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavbars__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNavbars__ArgProps,
          internalVariantPropNames: PlasmicNavbars__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbars__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavbars";
  } else {
    func.displayName = `PlasmicNavbars.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbars = Object.assign(
  // Top-level PlasmicNavbars renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbarWithTwoRows: makeNodeComponent("navbarWithTwoRows"),
    navbarWithTwoRowsOnAccent: makeNodeComponent("navbarWithTwoRowsOnAccent"),
    navbarWithAvatarOnAccent: makeNodeComponent("navbarWithAvatarOnAccent"),
    navbarWithAvatar: makeNodeComponent("navbarWithAvatar"),

    // Metadata about props expected for PlasmicNavbars
    internalVariantProps: PlasmicNavbars__VariantProps,
    internalArgProps: PlasmicNavbars__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicNavbars;
/* prettier-ignore-end */
