const StyleDictionary = require("style-dictionary");
const {
    registerTransforms,
    transforms,
  } = require("@tokens-studio/sd-transforms");

const { promises } = require("node:fs");

registerTransforms(StyleDictionary);

StyleDictionary.registerTransformGroup({
    name: "custom/tokens-studio",
    transforms: [...transforms, "attribute/cti", "name/cti/kebab"],
  });

const tokenFilter = (cat) => (token) => token.attributes.category === cat;

const generateFilesArr = (tokensCategories, theme) => {
    return tokensCategories.map((cat) => ({
      filter: tokenFilter(cat),
      destination: `./src/components/${cat}/tokens/${cat}-${theme.toLowerCase()}.tokens`,
      format: "css/variables",
      options: {
        selector: ":host",
        fileHeader: "autoGeneratedFileHeader",
      },
    }));
  };

async function run() {
    const $themes = JSON.parse(await promises.readFile("./src/tokens/$themes.json"));
    const configs = $themes.map((theme) => ({
        source: Object.entries(theme.selectedTokenSets)
          .filter(([, val]) => val !== "disabled")
          .map(([tokenset]) => `./src/tokens/${tokenset}.json`),
        fileHeader: {
          autoGeneratedFileHeader: () => {
            return [`Do not edit directly, this file was auto-generated`];
          },
        },
        platforms: {
          css: {
            transformGroup: "custom/tokens-studio",
            files: generateFilesArr(
              [
                "accordion",
                "accordionButton",
                "accordionIcon",
                "accordionItem",
                "accordionPanel",
                "alert",
                "alertDialog",
                "aspectRatio",
                "avatar",
                "avatarBadge",
                "avatarGroup",
                "badge",
                "box",
                "breadcrumb",
                "breadcrumbItem",
                "breadcrumbLink",
                "breadcrumbSeparator",
                "button",
                "buttonGroup",                
                "card",
                "cardBody",
                "cardFooter",
                "cardHeader",
                "center",
                "checkbox",
                "checkboxGroup",
                "circularProgress",
                "closeButton",
                "code",
                "container",
                "divider",
                "drawer",
                "editable",
                "flex",
                "formControl",
                "formErrorMessage",
                "formHelperText",
                "formLabel",
                "grid",
                "heading",
                "highlight",
                "hStack",
                "icon",
                "iconButton",
                "image",
                "input",
                "kbd",
                "link",
                "linkOverlay",
                "list",
                "menu",
                "modal",
                "modalBody",
                "modalCloseButton",
                "modalContent",
                "modalFooter",
                "modalHeader",
                "modalOverlay",
                "numberDecrementStepper",
                "numberIncrementStepper",
                "numberInput",
                "numberInputField",
                "numberInputStepper",
                "pinInput",
                "pinInputField",
                "popover",
                "popoverArrow",
                "popoverBody",
                "popoverCloseButton",
                "popoverContent",
                "popoverHeader",
                "popoverTrigger",
                "portal",
                "progress",
                "radio",
                "radioGroup",
                "rangeSlider",
                "select",
                "showHide",
                "simpleGrid",
                "skeleton",
                "skipNav",
                "slider",
                "spinner",
                "stack",
                "stat",
                "statArrow",
                "statHelpText",
                "statLabel",
                "statNumber",
                "stepper",
                "switch",
                "tab",
                "table",
                "tableCaption",
                "tableContainer",
                "tabList",
                "tabPanel",
                "tabPanels",
                "tabs",
                "tag",
                "tagCloseButton",
                "tagLabel",
                "tagLeftIcon",
                "tagRightIcon",
                "tbody",
                "td",
                "text",
                "textarea",
                "tfoot",
                "th",
                "thead",
                "toast",
                "tooltip",
                "tr",
                "transitions",
                "visuallyHidden",
                "vStack",
                "wrap",
              ], theme.name),
          },
        },
      }));


      
    configs.forEach((cfg) => {
        const sd = StyleDictionary.extend(cfg);
        sd.cleanAllPlatforms();
        sd.buildAllPlatforms();
      });
}

run();